# -*- coding: utf-8 -*-
"""Vegetation water consumption.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J47wTnxZSdylb0xYfiPAo5tNJG60svfk
"""

!pip install -q --upgrade xee
!pip install -q -U geemap

import ee
import geemap
import xarray as xr
import matplotlib.pyplot as plt
import numpy as np
from shapely.geometry import shape
from xee import helpers

ee.Authenticate()

ee.Initialize(
    project='ee-lavibas23',
    opt_url='https://earthengine-highvolume.googleapis.com'
)

roi = ee.Geometry.Rectangle([
    80.85, 7.65,
    81.15, 8.05
])

Map = geemap.Map(
    basemap='HYBRID'
)

Map.centerObject(roi, 9)

Map.addLayer(
    roi,
    {'color': 'red'},
    'ROI'
)

Map

def add_ndvi(img):

    qa = img.select('QA60')

    cloud_mask = qa.bitwiseAnd(1 << 10).eq(0)

    sr = img.divide(10000)

    ndvi = sr.normalizedDifference(
        ['B8', 'B4']
    ).rename('ndvi')

    return ndvi.updateMask(
        cloud_mask
    ).copyProperties(
        img,
        ['system:time_start']
    )

s2 = (
    ee.ImageCollection(
        'COPERNICUS/S2_SR_HARMONIZED'
    )
    .filterBounds(roi)
    .filterDate(
        '2023-01-01',
        '2024-01-01'
    )
    .filter(
        ee.Filter.lt(
            'CLOUDY_PIXEL_PERCENTAGE',
            20
        )
    )
    .map(add_ndvi)
)

print(
    'Sentinel-2 Collection:',
    s2.size().getInfo()
)

ndvi_max = s2.max()

veg_mask = (
    ndvi_max.gt(0.5)
    .selfMask()
)

veg_area = (
    veg_mask.multiply(
        ee.Image.pixelArea()
    )
    .reduceRegion(
        reducer=ee.Reducer.sum(),
        geometry=roi,
        scale=10,
        maxPixels=1e13
    )
    .values()
    .get(0)
)

veg_area_m2 = veg_area.getInfo()

print(
    'Vegetated Area (m²):',
    veg_area_m2
)

roi_shape = shape(
    roi.getInfo()
)

grid_params = helpers.fit_geometry(
    geometry=roi_shape,
    grid_crs='EPSG:4326',
    grid_scale=(0.0001, -0.0001)
)

ds_ndvi = xr.open_dataset(
    s2,
    engine='ee',
    **grid_params
)

ds_ndvi

ds_ndvi_max = ds_ndvi.max(
    dim='time'
)

plt.figure(figsize=(8,7))

ds_ndvi_max.ndvi.plot(
    x='x',
    y='y',
    cmap='Greens',
    robust=True
)

plt.title(
    'Maximum NDVI'
)

plt.show()

veg_xr = (
    ds_ndvi_max.ndvi > 0.5
)

plt.figure(figsize=(8,7))

veg_xr.plot(
    x='x',
    y='y',
    cmap='Greens'
)

plt.title(
    'Vegetation Mask'
)

plt.show()

et = (
    ee.ImageCollection(
        "MODIS/061/MOD16A2"
    )
    .select('ET')
    .filterBounds(roi)
    .filterDate(
        '2023-01-01',
        '2024-01-01'
    )
)

print(
    'MODIS ET Collection:',
    et.size().getInfo()
)

grid_params_et = helpers.fit_geometry(
    geometry=roi_shape,
    grid_crs='EPSG:4326',
    grid_scale=(0.005, -0.005)
)

ds_et = xr.open_dataset(
    et,
    engine='ee',
    **grid_params_et
)

# MOD16 scaling factor
ds_et = ds_et * 0.1

ds_et

ds_et.ET.plot(
    x='x',
    y='y',
    cmap='gist_earth_r',
    col='time',
    col_wrap=4,
    robust=True
)

plt.suptitle(
    'Evapotranspiration'
)

plt.show()

et_mean = ds_et.mean(
    dim=['x','y'],
    skipna=True
)

et_mean_vals = et_mean.ET.values

print(
    et_mean_vals
)

water_consumption = (
    et_mean_vals * veg_area_m2
) / 1000

print(
    'Water Consumption (m³)'
)

print(
    water_consumption
)

plt.figure(figsize=(10,5))

plt.plot(
    et_mean.time.values,
    water_consumption,
    marker='o'
)

plt.title(
    'Vegetation Water Consumption'
)

plt.xlabel('Time')

plt.ylabel(
    'Water Consumption (m³)'
)

plt.grid(ls=':')

plt.show()